=== dracko/XML/HolaMundoApp/HolaMundo/SOA/xsd/VentaArticuloSchema.xsd
<?xml version="1.0" encoding="windows-1252" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.example.org"
            targetNamespace="http://www.example.org" elementFormDefault="qualified">
  <xsd:element name="resumen">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="fecha" type="xsd:date"/>
        <xsd:element name="cantidadDeProductos" type="xsd:integer"/>
        <xsd:element name="total" type="xsd:integer"/>
        <xsd:element name="articulos">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="articulo" maxOccurs="unbounded">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="id"/>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
</xsd:schema>

=== dracko/XML/HolaMundoApp/HolaMundo/SOA/Transformations/XSLNonDeployedFiles/Mapeo04-Target.xml
<?xml version = '1.0' encoding = 'UTF-8'?>
<ns0:resumen xmlns:ns0="http://www.example.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org file:/C:/JDeveloper/mywork/HolaMundoApp/HolaMundo/SOA/xsd/VentaArticuloSchema.xsd">
   <ns0:articulos>
      <ns0:articulo>
         <ns0:id/>
      </ns0:articulo>
      <ns0:articulo>
         <ns0:id/>
      </ns0:articulo>
      <ns0:articulo>
         <ns0:id/>
      </ns0:articulo>
   </ns0:articulos>
</ns0:resumen>
